version: '3'
name: diet-bot

networks:
  diet-bot-network:
    driver: bridge

services:
  diet-bot-postgres:
    image: postgres:15.3-alpine3.18
    container_name: diet-bot-postgres
    networks:
      - diet-bot-network

    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diet-bot
    ports:
      - "5432:5432"

  diet-bot-pgadmin:
    container_name: diet-bot-pgadmin
    image: dpage/pgadmin4:8.6
    restart: always
    networks:
      - diet-bot-network
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=admin